### ISSUE TITLE
JS packaging

### ISSUE THREAD

**Issue by steinbro** [soundscape-community/soundscape-web-client#2]
We currently pull in some third party libraries (Turf.js, Leaflet.js) by linking to CDN-hosted versions, and our own code is split across many separate JS files for modularity. This should really all be packaged up and compiled down to a single JS file. Investigate using [Webpack](https://webpack.js.org/) or similar tools.

Consider using for audio assets as well.

**Comment by ragar3** [comment]
When you say "compiled to a single JS file" is this referring to a "bundle.js" file (as per Webpack documentation) that is then referenced in index.html? It seems there are a couple different ways to use Webpack so we aren't totally sure what the end goal is.

**Comment by steinbro** [comment]
We've started using Vite as of #27, so the JS packaging is covered now.
