### ISSUE TITLE
iOS/Safari: Compass arrow not shown

### ISSUE THREAD

**Issue by steinbro** [soundscape-community/soundscape-web-client#40]
Error in console when enabling the primary location tracking mode:

> Unhandled Promise Rejection: NotAllowedError: Requesting device orientation access requires a user gesture to prompt

This seems to be an iOS-specific thing: https://dev.to/li/how-to-requestpermission-for-devicemotion-and-deviceorientation-events-in-ios-13-46g2

It's weird, because we do trigger the permission request via a user gesture (button click). Maybe Vue added a level of indirection that makes Safari think it's some other kind of event?

@sebastianovide I assume you're still seeing the compass arrow on Android?

**Comment by sebastianovide** [comment]
nop. I don't see it in anymore anywhere (chrome, firefox and android app)

**Comment by steinbro** [comment]
Should be fixed now. See comment in #39 for an explanation of what was going on in iOS.
